type TreeQueryExecutor = (
  query: string,
  options?: { databaseName?: string },
) => Promise<{ success: boolean; data?: any; error?: string }>;

export interface PostgresTableDefinitionParams {
  schema: string;
  table: string;
  databaseName?: string;
}

interface ColumnRow {
  name: string;
  type: string;
  not_null: boolean;
  default: string | null;
  identity: string | null;
  generated: string | null;
}

interface ConstraintRow {
  name: string;
  type: string;
  definition: string;
}

interface CommentRow {
  name: string;
  comment: string;
}

interface NamedDefinitionRow {
  name: string;
  definition: string;
}

function quoteIdent(name: string): string {
  return `"${String(name).replace(/"/g, '""')}"`;
}

function quoteLiteral(value: string): string {
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** json/jsonb columns may arrive pre-parsed or as strings depending on driver. */
function asArray<T>(value: unknown): T[] {
  if (Array.isArray(value)) return value as T[];
  if (typeof value === "string") {
    try {
      const parsed = JSON.parse(value);
      return Array.isArray(parsed) ? (parsed as T[]) : [];
    } catch {
      return [];
    }
  }
  return [];
}

function formatColumnLine(col: ColumnRow): string {
  let line = `${quoteIdent(col.name)} ${col.type}`;
  if (col.generated === "s" && col.default) {
    line += ` GENERATED ALWAYS AS (${col.default}) STORED`;
  } else if (col.identity === "a") {
    line += " GENERATED ALWAYS AS IDENTITY";
  } else if (col.identity === "d") {
    line += " GENERATED BY DEFAULT AS IDENTITY";
  }
  if (col.not_null) {
    line += " NOT NULL";
  }
  if (col.default && col.generated !== "s" && !col.identity) {
    line += ` DEFAULT ${col.default}`;
  }
  return line;
}

/**
 * Build a TablePlus-style SQL script describing a Postgres table or view:
 * CREATE TABLE (columns + constraints), table/column comments, indexes
 * (excluding those backing constraints), and triggers.
 *
 * Shared by the Postgres-family drivers (postgresql, cloudsql-postgres) which
 * differ only in how they execute queries.
 */
export async function buildPostgresTableDefinition(
  executeQuery: TreeQueryExecutor,
  params: PostgresTableDefinitionParams,
): Promise<{ success: boolean; definition?: string; error?: string }> {
  const safeSchema = String(params.schema).replace(/'/g, "''");
  const safeTable = String(params.table).replace(/'/g, "''");

  const result = await executeQuery(
    `SELECT
       c.relkind::text AS relkind,
       obj_description(c.oid, 'pg_class') AS table_comment,
       CASE WHEN c.relkind IN ('v', 'm')
         THEN pg_get_viewdef(c.oid, true) END AS view_definition,
       CASE WHEN c.relkind = 'p'
         THEN pg_get_partkeydef(c.oid) END AS partition_key,
       (
         SELECT coalesce(json_agg(json_build_object(
             'name', a.attname,
             'type', format_type(a.atttypid, a.atttypmod),
             'not_null', a.attnotnull,
             'default', pg_get_expr(ad.adbin, ad.adrelid),
             'identity', nullif(a.attidentity::text, ''),
             'generated', nullif(a.attgenerated::text, '')
           ) ORDER BY a.attnum), '[]'::json)
         FROM pg_attribute a
         LEFT JOIN pg_attrdef ad
           ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
         WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
       ) AS columns,
       (
         SELECT coalesce(json_agg(json_build_object(
             'name', con.conname,
             'type', con.contype,
             'definition', pg_get_constraintdef(con.oid, true)
           ) ORDER BY CASE con.contype
               WHEN 'f' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2
               WHEN 'x' THEN 3 ELSE 4 END,
             con.conname), '[]'::json)
         FROM pg_constraint con
         WHERE con.conrelid = c.oid
           AND con.contype IN ('p', 'f', 'u', 'c', 'x')
       ) AS constraints,
       (
         SELECT coalesce(json_agg(json_build_object(
             'name', a.attname,
             'comment', d.description
           ) ORDER BY a.attnum), '[]'::json)
         FROM pg_attribute a
         JOIN pg_description d
           ON d.objoid = c.oid
          AND d.classoid = 'pg_class'::regclass
          AND d.objsubid = a.attnum
         WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
       ) AS column_comments,
       (
         SELECT coalesce(json_agg(json_build_object(
             'name', ci.relname,
             'definition', pg_get_indexdef(i.indexrelid)
           ) ORDER BY ci.relname), '[]'::json)
         FROM pg_index i
         JOIN pg_class ci ON ci.oid = i.indexrelid
         WHERE i.indrelid = c.oid
           AND NOT EXISTS (
             SELECT 1 FROM pg_constraint pc WHERE pc.conindid = i.indexrelid
           )
       ) AS indexes,
       (
         SELECT coalesce(json_agg(json_build_object(
             'name', t.tgname,
             'definition', pg_get_triggerdef(t.oid, true)
           ) ORDER BY t.tgname), '[]'::json)
         FROM pg_trigger t
         WHERE t.tgrelid = c.oid AND NOT t.tgisinternal
       ) AS triggers
     FROM pg_class c
     JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = '${safeSchema}'
       AND c.relname = '${safeTable}'
       AND c.relkind IN ('r', 'p', 'v', 'm', 'f');`,
    { databaseName: params.databaseName },
  );

  if (!result.success) {
    return {
      success: false,
      error: result.error || "Failed to fetch table definition",
    };
  }
  const row = result.data?.[0];
  if (!row) {
    return {
      success: false,
      error: `Table "${params.schema}"."${params.table}" not found`,
    };
  }

  const relkind = String(row.relkind || "r");
  const qualifiedName = `${quoteIdent(params.schema)}.${quoteIdent(params.table)}`;
  const columns = asArray<ColumnRow>(row.columns);
  const constraints = asArray<ConstraintRow>(row.constraints);
  const columnComments = asArray<CommentRow>(row.column_comments);
  const indexes = asArray<NamedDefinitionRow>(row.indexes);
  const triggers = asArray<NamedDefinitionRow>(row.triggers);

  const sections: string[] = [];

  if (relkind === "v" || relkind === "m") {
    const keyword = relkind === "m" ? "MATERIALIZED VIEW" : "VIEW";
    const body = String(row.view_definition || "").replace(/;\s*$/, "");
    sections.push(
      `-- View Definition\nCREATE ${keyword} ${qualifiedName} AS\n${body};`,
    );
  } else {
    const bodyLines = [
      ...columns.map(formatColumnLine),
      ...constraints.map(con =>
        con.type === "p"
          ? con.definition
          : `CONSTRAINT ${quoteIdent(con.name)} ${con.definition}`,
      ),
    ];
    const partitionBy = row.partition_key
      ? ` PARTITION BY ${row.partition_key}`
      : "";
    sections.push(
      `-- Table Definition\nCREATE TABLE ${qualifiedName} (\n    ${bodyLines.join(",\n    ")}\n)${partitionBy};`,
    );
  }

  if (row.table_comment) {
    const keyword =
      relkind === "v" || relkind === "m" ? "VIEW" : "TABLE";
    sections.push(
      `-- ${keyword === "VIEW" ? "View" : "Table"} Comment\nCOMMENT ON ${keyword} ${qualifiedName} IS ${quoteLiteral(String(row.table_comment))};`,
    );
  }

  if (columnComments.length > 0) {
    const lines = columnComments.map(
      cc =>
        `COMMENT ON COLUMN ${qualifiedName}.${quoteIdent(cc.name)} IS ${quoteLiteral(cc.comment)};`,
    );
    sections.push(`-- Column Comments\n${lines.join("\n")}`);
  }

  if (indexes.length > 0) {
    sections.push(
      `-- Indices\n${indexes.map(ix => `${ix.definition};`).join("\n")}`,
    );
  }

  if (triggers.length > 0) {
    sections.push(
      `-- Triggers\n${triggers.map(tr => `${tr.definition};`).join("\n")}`,
    );
  }

  return { success: true, definition: sections.join("\n\n") + "\n" };
}
