packages:
  - .
  - app
  - api
  - docs
  - packages/*
allowBuilds:
  '@mui/x-telemetry': false
  bcrypt: false
  core-js: false
  cpu-features: false
  electron: true
  electron-winstaller: false
  es5-ext: false
  esbuild: true
  mongodb-memory-server: false
  protobufjs: false
  sharp: false
  sqlite3: false
  ssh2: true
  workerd: false
ignoredBuiltDependencies:
  - bcrypt
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@3.0.124'
  - '@ai-sdk/react@3.0.198'
  - ai@6.0.196
