packages:
  - .
  - app
  - api
  - website
  - docs
ignoredBuiltDependencies:
  - bcrypt
onlyBuiltDependencies:
  - esbuild
  - sqlite3
  - sharp
  - protobufjs
  - es5-ext
  - "@mui/x-telemetry"
  - workerd
